### PR TITLE
set char to string

### PR DESCRIPTION
**Pull request by dickeyxxx**
the fix on the `heroku-cli` for this is in master, but I haven't released it yet

### CODE REVIEW

**Comment by lmarburger** [comment]
:heart: Let me know when it's safe to merge. Thanks! :heart:

**Comment by dickeyxxx** [comment]
it's safe!

**Comment by dickeyxxx** [comment]
also, the null command issue is resolved, but it is awaiting the next CLI release which I'll probably do early next week

**Comment by lmarburger** [comment]
Merged in 7660280

**Pull request closed without merging**
