### PR TITLE
change command from pt:logs to just pt

### PR DESCRIPTION
**Pull request by dickeyxxx**
per @craigkerstiens's suggestion

### CODE REVIEW

**Comment by craigkerstiens** [comment]
I was actually thinking it might be useful to output general help text if only `pt` was run.

**Comment by dickeyxxx** [comment]
ah any thoughts @troy?

**Comment by lmarburger** [comment]
I'm all for making the default command simply `pt`. It'd be nice to also support `pt:logs`. No need to break muscle memory and/or scripts.

**Comment by craigkerstiens** [comment]
Is there a hope to add other commands in the future? If so then having `pt` just output essentially the help could be good, but if never expecting other commands then having both work makes sense, just my two cents.

**Comment by lmarburger** [comment]
That's a good point. Even if we do add new commands, it's hard to imagine anything other than the current `pt:logs` being far and away the reason most people use the plug-in. Simply aliasing `pt:logs` as `pt` could be all we need. (Definitely don't want to _change_ the command.)

We'll talk about it.

**Comment by troy** [comment]
I echo @lmarburger's and @craigkerstiens' point. As long as the `pt:logs` continues to work, having `pt` default to it seems like the way to go.

**Comment by lmarburger** [comment]
Merging this PR and then re-adding the `pt:logs` legacy command.

Thanks, @dickeyxxx and @craigkerstiens!

**Comment by lmarburger** [comment]
It's live!

```
$ heroku plugins:install heroku-papertrail
Installing plugin heroku-papertrail... done

$ heroku help pt
Usage: heroku pt [QUERY]

   -t, --tail          # stream new logs in as they're received


   Shows the most recent logs matching an optional search query.

Additional commands, type "heroku help COMMAND" for more details:

  pt:logs [QUERY]  #  Identical to `pt` kept only for backwards compatibility
```

**Comment by lmarburger** [comment]
I don't know how I managed to break github, but I merged this commit in a1bc8f0

**Pull request closed without merging**
